site_name: Appsec Discovery
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
  language: en
  features:
    - navigation.indexes
    - navigation.top
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
nav:
  - About: 
    - 'index.md'
  - Quik start: 
    - 'quikstart/index.md'
  - Installation: 
    - 'install/index.md'
  - Parsers: 
    - 'parsers/index.md'
  - Contribution: 
    - 'contrib/index.md'